application/app/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index,name="index"),
    url(r'^panel/$', login_required(panel),name="panel"),
    url(r'^panel/ingreso$', login_required(muestra_1),name="muestra_1"),
    url(r'^panel/listado$', login_required(muestra_2),name="muestra_2"),


]

application/application/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
	  # Django JET URLS
	url(r'^login/$', auth_views.login ,{'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls',namespace="app")),

]

application/app/models.py
from django.db import models

# Create your models here.

application/app/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.shortcuts import redirect

# Create your views here.
def index(request):
	return render(request,'landing_page/index.html')
def panel(request):
	return render(request,'panel_admin/index.html')
def muestra_1(request):
	return render(request,'panel_admin/muestra.html')
def muestra_2(request):
	return render(request,'panel_admin/muestra_2.html')

application/templates/panel_admin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--================================================================================
	Item Name: Materialize - Material Design Admin Template
	Version: 3.1
	Author: GeeksLabs
	Author URL: http://www.themeforest.net/user/geekslabs
================================================================================ -->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">

    <title>Vida Plena</title>


    <!-- Favicons-->
    <link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="{% static 'images/favicon/mstile-144x144.png'%}">
    <!-- For Windows Phone -->



    <!-- CORE CSS-->
    <link href="{% static 'css/materialize.css'%}" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static 'css/style.css'%}" type="text/css" rel="stylesheet" media="screen,projection">
    <!-- Custome CSS-->

    <link href="{% static 'css/custom/custom.css'%}" type="text/css" rel="stylesheet" media="screen,projection">

    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="{% static 'js/plugins/perfect-scrollbar/perfect-scrollbar.css'%}" type="text/css" rel="stylesheet" media="screen,projection">


</head>

<body>
    <!-- Start Page Loading -->
    <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
    <!-- End Page Loading -->

    <!-- //////////////////////////////////////////////////////////////////////////// -->

    <!-- START HEADER -->
    <header id="header" class="page-topbar">
        <!-- start header nav-->
        <div class="navbar-fixed">
            <nav class="navbar-color">
                <div class="nav-wrapper">

                    <ul class="left">
                      <li><h1 class="logo-wrapper"><a href="{% url 'app:panel' %}" class="brand-logo darken-1"><img src="{% static 'assets/img/logo.png'%}" alt="materialize logo"></a> <span class="logo-text">Vida Plena</span></h1></li>

                    </ul>
                    <div class="header-search-wrapper hide-on-med-and-down">
                        <i class="mdi-action-search"></i>
                        <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Buscar"/>
                    </div>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown"><i class="mdi-social-notifications"></i></a></li>
                    </ul>

                    <!-- notifications-dropdown -->
                    <ul id="notifications-dropdown" class="dropdown-content">
                      <li>
                        <h5>NOTIFICATIONS <span class="new badge">5</span></h5>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a href="#!"><i class="mdi-action-add-shopping-cart"></i> A new order has been placed!</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-action-stars"></i> Completed the task</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">3 days ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-action-settings"></i> Settings updated</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">4 days ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-editor-insert-invitation"></i> Director meeting started</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">6 days ago</time>
                      </li>
                      <li>
                        <a href="#!"><i class="mdi-action-trending-up"></i> Generate monthly report</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">1 week ago</time>
                      </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- end header nav-->
    </header>
    <!-- END HEADER -->

    <!-- //////////////////////////////////////////////////////////////////////////// -->

    <!-- START MAIN -->
    <div id="main">
        <!-- START WRAPPER -->
        <div class="wrapper">

            <!-- START LEFT SIDEBAR NAV-->
            <aside id="left-sidebar-nav">
                <ul id="slide-out" class="side-nav fixed leftside-navigation">
                <li class="user-details cyan darken-2">
                <div class="row">
                    <div class="col col s8 m8 l8">
                        <ul id="profile-dropdown" class="dropdown-content">
                            <li><a href="#"><i class="mdi-action-face-unlock"></i> Profile</a>
                            </li>
                            <li><a href="#"><i class="mdi-action-settings"></i> Settings</a>
                            </li>
                            <li><a href="#"><i class="mdi-communication-live-help"></i> Help</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="mdi-action-lock-outline"></i> Lock</a>
                            </li>
                            <li><a href="{% url 'logout' %}"><i class="mdi-hardware-keyboard-tab"></i> Logout</a>
                            </li>
                        </ul>
                        <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown">{{user.username}}<i class="mdi-navigation-arrow-drop-down right"></i></a>
                        <p class="user-roal">Administrator</p>
                    </div>
                </div>
                </li>
                <li class="bold {% if request.path == '/panel/' %}active{%endif%}"><a href="{% url 'app:panel' %}" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Inicio</a>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold active"><a class="collapsible-header waves-effect waves-cyan"><i class="mdi-action-view-carousel "></i> Control de Diezmos</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li class="bold {% if request.path == '/panel/ingreso' %}active{%endif%}"><a href="{% url 'app:muestra_1' %}">Ingresos</a>
                                    </li>
                                    <li class="bold {% if request.path == '/panel/listado' %}active{%endif%}"><a href="{% url 'app:muestra_2' %}">Egresos</a>
                                    <li><a href="{% url 'app:muestra_2' %}">Listado</a>
                                    <li><a href="{% url 'app:muestra_2' %}">Reportes</a>


                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li class="bold"><a class="collapsible-header waves-effect waves-cyan"><i class="mdi-action-view-carousel"></i> Control de Actividades</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li class="bold active"><a href="{% url 'app:muestra_1' %}">Registro </a>
                                    </li>
                                    <li><a href="{% url 'app:muestra_2' %}">Listados</a>
                                    <li><a href="{% url 'app:muestra_2' %}">Reportes</a>

                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
                <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
            </aside>
            <!-- END LEFT SIDEBAR NAV-->

            <!-- //////////////////////////////////////////////////////////////////////////// -->
            <div id="breadcrumbs-wrapper">
            <!-- Search for small screen -->
            <div class="header-search-wrapper grey hide-on-large-only">
                <i class="mdi-action-search active"></i>
                <input name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize" type="text">
            </div>
            <!-- START CONTENT -->
                {% block content %}
                {% endblock %}
            <!-- END CONTENT -->

            <!-- //////////////////////////////////////////////////////////////////////////// -->
            <!-- START RIGHT SIDEBAR NAV-->

            <!-- LEFT RIGHT SIDEBAR NAV-->

        </div>
        <!-- END WRAPPER -->

    </div>
    <!-- END MAIN -->
  <div class="fixed-action-btn" style="bottom: 50px; right: 19px;" >
      <a class="btn-floating btn-large tooltipped" href="{% url 'app:index' %}" data-position="left" data-delay="50" data-tooltip="Pagina de Inicio">
        <i class="mdi-action-home"></i>
      </a>
  </div>


    <!-- //////////////////////////////////////////////////////////////////////////// -->

    <!-- START FOOTER -->
    <footer class="page-footer">
        <div class="footer-copyright">
            <div class="container">
                Copyright © 2018 <a class="grey-text text-lighten-4" href="https://vidaplena.pythonanywhere.com" target="_blank">Vida Plena</a> Todos los derechos reservados.

                <span class="right"> Desarrollado por Humberto Andueza y Wilersy Hidalgo</span>
            </div>
        </div>
    </footer>
    <!-- END FOOTER -->


    <!-- ================================================
    Scripts
    ================================================ -->

    <!-- jQuery Library -->
    <script type="text/javascript" src="{% static 'js/plugins/jquery-1.11.2.min.js'%}"></script>
    <!--materialize js-->
    <script type="text/javascript" src="{% static 'js/materialize.js'%}"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="{% static 'js/plugins/perfect-scrollbar/perfect-scrollbar.min.js'%}"></script>




    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="{% static 'js/plugins.min.js'%}"></script>
    <!--custom-script.js - Add your own theme custom JS-->
    <script type="text/javascript" src="{% static 'js/custom-script.js'%}"></script>
    <!-- Toast Notification -->
    <script type="text/javascript">
        $(document).ready(function(){
            $('.tooltipped').tooltip({delay: 50});
          });
        $('.datepicker').pickadate({
        monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        weekdaysFull: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
        selectMonths: true,
        selectYears: 100, // Puedes cambiarlo para mostrar más o menos años
        today: 'Hoy',
        clear: 'Limpiar',
        close: 'Ok',
        labelMonthNext: 'Siguiente mes',
        labelMonthPrev: 'Mes anterior',
        labelMonthSelect: 'Selecciona un mes',
        labelYearSelect: 'Selecciona un año',
});
    </script>
</body>

</html>

application/templates/panel_admin/index.html
{% extends "panel_admin/base.html" %}
{% load static %}
{% block content %}
<<<<<<< HEAD
<section id="content" class="bg">
	<div class="container">
		<div class="row ">
			<div class="col col s12 m12 l12 center" style="margin-top: 15vh;margin-bottom: 14vh;">
			<img  style="max-width: 40%;height: auto" src="{% static 'images/logo.png' %}"> <!-- notice the "circle" class -->
			<h4 style="font-weight: bold;">Bienvenid@ {{request.user.username}} al panel Admin de la <br> Aplicación Web de la Iglesia Vida Plena</h4>
		    </div>
=======
<div class="container">
	<div class="row">
		<div class="col s12 m8 l8">
			<h1>Hello {{user.first_name}} {{user.last_name}} </h1>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
			<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</p>
>>>>>>> 2cd3228e497f27283205df71cf46e1116e358ce8
		</div>
	</div>
</section>

{% endblock%}

application/templates/panel_admin/muestra.html
{% extends "panel_admin/base.html" %}

{% block content %}
<section id="content" class="bg" >
<div class="container">
    <div class="section" >
        <div class="row">
            <div class="section"  style="margin-top: 13vh;">
              <h3 class="header center">Registro de Diezmos</h3>
            </div>
        </div>
        
        <div class="row">
            <div class="col s10 offset-s1 m6 offset-m3 ">
              <input class="datepicker picker__input" readonly="" placeholder="Fecha" id="P475155353" tabindex="-1" aria-haspopup="true" aria-expanded="false" aria-readonly="false" aria-owns="P475155353_root" type="text">
            </div>
        </div>
        <div class="row">
            <div class="input-field col m3 s10 offset-m3  offset-s1">
              <input id="icon_prefix3" class="validate" type="text">
              <label for="icon_prefix3" class="">Nombre del miembro</label>
            </div>
            <div class="input-field col m3 s10 offset-s1 ">
                <input id="icon_prefix3" class="validate" type="text">
                <label for="icon_prefix3" class="">Apellido del miembro</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col m3 s10 offset-m3  offset-s1">
                <input id="icon_telephone" class="validate" type="tel">
                <label for="icon_telephone" class="active">Cantidad de Diezmos</label>
            </div>
            <div class="input-field col m3 s10 offset-s1 ">            
                <select class="initialized">
                    <option value="" disabled="" selected="">Metodo de Pago</option>
                    <option value="1">Efectivo</option>
                    <option value="2">Transferencia</option>
                </select>
            </div>
        </div>
        <div class="row" style="margin-bottom: 15vh;">
            <div class="col s12 center">
                <p><a class="btn waves-effect waves-light blue">Guardar Registro</a></p>
            </div>
        </div>
    </div>
</div>
</section>



{% endblock%}

application/templates/panel_admin/muestra_2.html
{% extends "panel_admin/base.html" %}

{% block content %}
<section id="content">
<div class="container">
  <div class="section">
    <div id="striped-table">
      <h4 class="header center">Listado de Diezmos</h4>
      <div class="row">
        <div class="col s10 offset-s1">
          <table class="striped responsive-table">
            <thead>
              <tr>
                <th data-field="id">Nombre</th>
                <th data-field="name">Apellido</th>
                <th data-field="price">Cantidad</th>
                <th data-field="price">Fecha</th>

              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Jose</td>
                <td>Perez</td>
                <td>$2000</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Alan</td>
                <td>Montilla</td>
                <td>$3455.76</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Jonathan</td>
                <td>Montes</td>
                <td>$7555.00</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Rosa</td>
                <td>Nuñez</td>
                <td>$96666.99</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Jose</td>
                <td>Perez</td>
                <td>$2000</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Alan</td>
                <td>Montilla</td>
                <td>$3455.76</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Jonathan</td>
                <td>Montes</td>
                <td>$7555.00</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Rosa</td>
                <td>Nuñez</td>
                <td>$96666.99</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Jose</td>
                <td>Perez</td>
                <td>$2000</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Alan</td>
                <td>Montilla</td>
                <td>$3455.76</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Jonathan</td>
                <td>Montes</td>
                <td>$7555.00</td>
                <td>17/12/2019</td>
              </tr>
              <tr>
                <td>Rosa</td>
                <td>Nuñez</td>
                <td>$96666.99</td>
                <td>17/12/2019</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

</div>

</div>
</section>

{% endblock %}